### PR TITLE
Release v2.0.0

### LINKED ISSUE #75: Release Ap-Nimbus v2.0.0
### [appredict-docker](https://github.com/CardiacModelling/appredict-docker)

- [x] Update to [Chaste 2024.1](https://github.com/Chaste/Chaste/releases/tag/2024.1) and [ApPredict 2024.1](https://github.com/Chaste/ApPredict/releases/tag/v2024.1)
- [x] Upgrade base image to debian bullseye.
- [x] Build [appredict-chaste-libs](https://hub.docker.com/r/cardiacmodelling/appredict-chaste-libs):2.0.0 docker image.
- [x] Build [appredict-no-emulators](https://hub.docker.com/r/cardiacmodelling/appredict-no-emulators):2.0.0 docker image.
- [x] Build [appredict-with-emulators](https://hub.docker.com/r/cardiacmodelling/appredict-with-emulators):2.0.0 docker image.
- [x] Release repository v2.0.0

### [ap-nimbus-app-manager](https://github.com/CardiacModelling/ap-nimbus-app-manager)
- [x] Update to appredict-with-emulators:2.0.0 base image.
- [x] Upgrade to [Node 20](https://nodejs.org/en/blog/release/v20.15.0).
- [x] Build [ap-nimbus-app-manager](https://hub.docker.com/r/cardiacmodelling/ap-nimbus-app-manager):2.0.0 docker image.
- [x] Release repository v2.0.0

### [ap-nimbus-client](https://github.com/CardiacModelling/ap-nimbus-client)
- [x] Support Python 3.12
- [x] Build [ap-nimbus-client](https://hub.docker.com/r/cardiacmodelling/ap-nimbus-client/):2.0.0 docker image.
- [x] User Acceptance Testing
- [x] Release repository v2.0.0

### [ap-nimbus](https://github.com/CardiacModelling/ap-nimbus)
- [x] Update RtD documentation.
- [x] Update submodules for appredict-docker, app-manager, and ap-nimbus client to v2.0.0.
- [ ] Release repository v2.0.0

### PR DESCRIPTION
**Pull request by kwabenantim**
* Supports #75

### CODE REVIEW

**Comment by kwabenantim** [comment]
The [appredict-docker](https://github.com/CardiacModelling/appredict-docker/) submodule has no commits since v1.0.0 and  doesn't need an update. Is it worth making a release so all three submodules are at v1.0.1 @mirams ?

**Comment by mirams** [comment]
Hmmm, has ApPredict itself had any updates that could migrate through to that? I would usually have done at least a copyright update but it appears I haven't had to touch the code yet this year!

**Comment by mirams** [comment]
But yeah, feel free to increment so it is obvious they go together

**Comment by kwabenantim** [comment]
It looks like those can be updated from Chaste and ApPredict 2021.1 to 2024.1 so all the ap-nimbus submodules can probably go up to v2.0.0.

**Review by mirams — APPROVED** [review]

**Pull request merged**
