### PR TITLE
More documentation adjustments.

### PR DESCRIPTION
**Pull request by flawmop**
- ap-nimbus `README.md` updated.
- Container and Running documentation updated.

Random `server.js` removed from repo root.

### CODE REVIEW

**Comment by flawmop** [comment]
Sorry Maurice, just found a few more changes to add to the above. Will include them and remove the "draft" status and let you know.

**Comment by MauriceHendrix** [comment]
So far the changes make sense to me, just let me know when you're done.

**Comment by flawmop** [comment]
@MauriceHendrix , I've made a few changes since you approved last week :

1. Merged in your recent changes to the docs.
2. Included your newly added docker env var properties (can you change https://github.com/CardiacModelling/ap-nimbus-client/blob/master/docker/env#L47 to `PRIVACY_NOTICE` please?)
3. Adjusted the original instructions to reflect the current situation regarding building/running the containers (I'll get in touch separately with some of the problems I've had running the containers).

**Comment by MauriceHendrix** [comment]
> @MauriceHendrix , I've made a few changes since you approved last week :
> 
> 1. Merged in your recent changes to the docs.
> 2. Included your newly added docker env var properties (can you change https://github.com/CardiacModelling/ap-nimbus-client/blob/master/docker/env#L47 to `PRIVACY_NOTICE` please?)
> 3. Adjusted the original instructions to reflect the current situation regarding building/running the containers (I'll get in touch separately with some of the problems I've had running the containers).

aah darn silly typo, (PRIVACY_NOTICE) I'll correct that

**Comment by flawmop** [comment]
If you're changing things, could you also change `ap_nimubs` to `ap_nimbus` in ap-nimbus-client too?

**Comment by MauriceHendrix** [comment]
> If you're changing things, could you also change `ap_nimubs` to `ap_nimbus` in ap-nimbus-client too?

never noticed that either sorry

**Comment by flawmop** [comment]
I was thinking of merging this PR today. Are you still ok for it to go ahead as I made quite a few more changes since a month ago?

**Pull request merged**
