### PR TITLE
ApPredict rename master

### PR DESCRIPTION
**Pull request by kwabenantim**
- Minor changes for renaming ApPredict master branch

### CODE REVIEW

**Comment by flawmop** [comment]
Hi @kwabenantim, would you mind if we removed this pull request and associated `appredict_rename_master` branch because there have been some big changes to Maurice's original "Updating ApPredict" document as part of https://github.com/CardiacModelling/ap-nimbus/blob/docs-appredict/docs/RtD/developer/updating-appredict/index.rst and as part of the changes I've just included the reference to the _main_ branch?

**Comment by mirams** [comment]
You mean delete/close this as superseded by another pull request that's coming in? Sounds fine to me.

**Comment by flawmop** [comment]
> You mean delete/close this as superseded by another pull request that's coming in? Sounds fine to me.

Yup! I'll create the pull request for `docs-appredict` branch.

**Comment by kwabenantim** [comment]
@flawmop sounds fine to me too.

**Pull request closed without merging**
